#!/usr/bin/env bash
set -x

###################################
##### Auto setup useful tools #####
###################################

[ -f $HOME/.bash/paths.bash ] && rm $HOME/.bash/paths.bash
PATHS_BASH=$HOME/.bash/

# FZF
if [[ ! -f $HOME/.fzf/bin/fzf ]]; then
  git clone https://github.com/junegunn/fzf.git $HOME/.fzf
  yes | $HOME/.fzf/install
  echo "export PATH=$HOME/.fzf/bin:\$PATH" >> ${PATHS_BASH}/paths.bash
fi

# DIFF-SO-FANCY
if [[ ! -f $HOME/bin/diff-so-fancy ]]; then
  mkdir $HOME/bin
  curl -o $HOME/bin/diff-so-fancy https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
  chmod +x $HOME/bin/diff-so-fancy
  echo "export PATH=$HOME/bin:\$PATH" >> ${PATHS_BASH}/paths.bash
fi




#######################
# TMUX
#######################

if [[ ! -d $HOME/.tmux/plugins/tpm ]]; then
  mkdir -p $HOME/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi


#######################
# Node for COC vim
#######################
if [[ ! -d $HOME/.node_local ]]; then
  mkdir -p $HOME/.node_local/node
  curl -sLo $HOME/.node_local/install-node.now.sh install-node.now.sh/lts
  chmod +x $HOME/.node_local/install-node.now.sh
  $HOME/.node_local/install-node.now.sh --prefix=$HOME/.node_local/node --yes
  echo "export PATH=$HOME/.node_local/node/bin:\$PATH" >> ${PATHS_BASH}/paths.bash
fi

# FORGIT
if [[ ! -f $HOME/forgit.plugin.zsh ]]; then
  curl -sL -o $HOME/forgit.plugin.zsh git.io/forgit
  echo "source $HOME/forgit.plugin.zsh" >> ${PATHS_BASH}/paths.bash
fi
