#!/usr/bin/env bash


# FZF
if [[ ! -z `which zsh` && ! -d ~/.oh-my-zsh ]]; then
	curl -Lo ~/install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
	sh ~/install.sh --unattended --keep-zshrc
  rm ~/install.sh
fi
