# Inserts a blank line between shell prompts
add_newline = true

[username]
disabled = true

# [custom.shell]
# command = "echo $SHELL | xargs basename"
# when = "echo 0"
# symbol = " "

[golang]
symbol = " "

[shell]
disabled = false
bash_indicator = "bash"

[directory]
fish_style_pwd_dir_length = 1
